Algoritmo TP3_Ej20_ConErrores_3
	Leer N
	Si (N%1)==0&(N%N)==0 Entonces
		Escribir N,' ES PRIMO'
	SiNo
		Escribir N,' NO ES PRIMO'
	FinSi
	// TODO NUMERO ES MULTIPLO DE 1 Y MULTIPLO DE SI MISMO
	// POR LO TANTO ESTE DIAGRAMA NO SIRVE SI 
	// BUSCAMOS DETERMINAR SI N ES PRIMO O NO LO ES.
	// FALTA DETERMINAR CUANTOS SON DIVISORES ENTRE 1 Y EL NUMERO N
FinAlgoritmo
